#!/bin/bash

# defining default variables

default_dir="/var/log/aptigrate"

# getting args

while getopts "o:c:" opt; do
    case $opt in
    o)
        backup_dir="$OPTARG"
        ;;
    c)
        cron_exp="$OPTARG"
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done

# check for all parameteres

# if [ -z "$backup_dir" ]; then
#     echo "Empty Param : provide a backup directory"
# fi

source ./cron/cron.sh

create_cron() {
    cronexp= generate_cron $1
    echo "$cronexp" 
    # | sudo tee $PWD/test.txt >/dev/null
}

create_backup() {
    apt list --manual-installed | sudo tee $backup_dir/backup.ap >/dev/null
}

if [ -z "$backup_dir" ]; then
    apt list --manual-installed | sudo tee $default_dir/backup.ap >/dev/null
else
    if [ -d "$backup_dir" ]; then
        # Take action if $DIR exists.
        echo "Creating a backup in "$backup_dir"..."
        create_backup
    else
        mkdir $backup_dir >/dev/null 2>/dev/null
    fi
fi

if [ -z "$cron_exp" ]; then
    test= create_cron $cron_exp
    echo $test
fi