#!/bin/bash

# default variables

default_dir="/var/log/aptigrate"
crondir="/var/spool/cron/crontabs"

# getting args

while getopts "o:c:" opt; do
    case $opt in
    o)
        backup_dir="$OPTARG"
        ;;
    c)
        cron_exp="$OPTARG"
        echo "$cron_exp"
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        exit 1
        ;;
    esac
done

# function definitions

create_cron() {
    cronexp="$1 /usr/local/bin/aptigrate"
    echo "$cronexp" | sudo tee $crondir/$USER>/dev/null
}

create_backup() {
    apt list --manual-installed | sudo tee $backup_dir/backup.ap >/dev/null
}

# creating backup

if [ -z "$backup_dir" ]; then
    apt list --manual-installed | sudo tee $default_dir/backup.ap >/dev/null
else
    if [ -d "$backup_dir" ]; then
        # Take action if $DIR exists.
        echo "Creating a backup in "$backup_dir"..."
        create_backup
    else
        mkdir $backup_dir >/dev/null 2>/dev/null
    fi
fi

# creating cron

if [ -z "$cron_exp" ]; then
    :
else
    create_cron "$cron_exp"
fi